AWSTemplateFormatVersion: 2010-09-09
Description: AppD Prod Stack ASGs with labeled nodes for manual scaling of ec2 
Transform: AppleTaggingStandard

Parameters:
  ConsoleInstanceType:
    Description: Instance type to launch
    Type: String
    Default:  t3.xlarge
  ControlInstanceType:
    Description: Instance type to launch
    Type: String
    Default: r5.8xlarge
  EUMInstanceType:
    Description: Instance type to launch
    Type: String
    Default: m5.4xlarge
  EUSInstanceType:
    Description: Instance type to launch
    Type: String
    Default: m5.8xlarge
  ImageId:
    Description: AMI Id
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /AIS/AMI/AmazonLinux2/Id
  CommonUserData:
    Type: String
    Default: | 
        #!/bin/bash
        set -eux
        groupadd -g 1009 appd
        useradd -u 1009 -g 1009 appd
        echo 'AppD@123' | sudo passwd --stdin appd
        mkdir /home/appd/.ssh
        touch /home/appd/.ssh/authorized_keys
        chown -R appd:appd /home/appd
        chmod 700 /home/appd/.ssh
        chmod 600 /home/appd/.ssh/authorized_keys
  
  APPDFileSystem:
    Type: String
    Default: | 
        # !/bin/bash
        mkdir /data1
        pvcreate /dev/xvdb
        vgcreate data1vg /dev/xvdb
        lvcreate -l 100%FREE -n data1 data1vg
        mkfs.xfs -L data1 /dev/mapper/data1vg-data1
        mount LABEL=data1 /data1
        sudo chmod 775  /data1
        UUID1=$(blkid /dev/mapper/data1vg-data1 | awk '{print $3}' | sed -e 's/"//g')
        echo "$UUID1              /data1           xfs    defaults         0 0" >> /etc/fstab

Resources:

  LoadBalancer1:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      LoadBalancerName: !Sub "${AWS::StackName}-AppDControlLoadBalancer"
      Subnets:
        - "{{resolve:ssm:/GNCS/0/Vpcs/0/denali-provided-enterprise-subnet/0/Id:1}}"
        - "{{resolve:ssm:/GNCS/0/Vpcs/0/denali-provided-enterprise-subnet/1/Id:1}}"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-AppD-LoadBalancer"
      LoadBalancerAttributes:
        - Key: load_balancing.cross_zone.enabled
          Value: "true"

  LoadBalancer2:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      LoadBalancerName: !Sub "${AWS::StackName}-AppDEUMLoadBalancer"
      Subnets:
        - "{{resolve:ssm:/GNCS/0/Vpcs/0/denali-provided-enterprise-subnet/0/Id:1}}"
        - "{{resolve:ssm:/GNCS/0/Vpcs/0/denali-provided-enterprise-subnet/1/Id:1}}"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-AppD-LoadBalancer"
      LoadBalancerAttributes:
        - Key: load_balancing.cross_zone.enabled
          Value: "true"

  LoadBalancer3:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      LoadBalancerName: !Sub "${AWS::StackName}-AppDEUSLoadBalancer"
      Subnets:
        - "{{resolve:ssm:/GNCS/0/Vpcs/0/denali-provided-enterprise-subnet/0/Id:1}}"
        - "{{resolve:ssm:/GNCS/0/Vpcs/0/denali-provided-enterprise-subnet/1/Id:1}}"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-AppD-LoadBalancer"
      LoadBalancerAttributes:
        - Key: load_balancing.cross_zone.enabled
          Value: "true"
       

   
  ControlTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        Name: !Sub "${AWS::StackName}ControlTG"
        Port: 9080
        Protocol: HTTP
        TargetType: instance
        HealthCheckPort: "9080"
        TargetGroupAttributes:
          - Key: deregistration_delay.timeout_seconds
            Value: "20"
        VpcId: !ImportValue ais-provided-vpc-VPCID
        Tags:
          - Key: Project
            Value: !Sub "${AWS::StackName} Appd-ControlTG"
  ControlListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
          - Type: forward
            TargetGroupArn:
              Ref: ControlTargetGroup
        LoadBalancerArn: !Ref "LoadBalancer1"
        Port: 443
        Protocol: HTTPS
        Certificates: 
          - CertificateArn: arn:aws:acm:us-west-2:597823015631:certificate/9d6a1f3d-aa01-4d41-925e-440123441c3b
        SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06

 
  EUMTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        Name: !Sub "${AWS::StackName}EUM-TG"
        Port: 9092
        Protocol: HTTP
        HealthCheckPort: "9092"
        TargetGroupAttributes:
          - Key: deregistration_delay.timeout_seconds
            Value: "20"
        VpcId: !ImportValue ais-provided-vpc-VPCID
        Tags:
          - Key: Project
            Value: !Sub "${AWS::StackName} Appd-EUMTG"
  EUMListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
          - Type: forward
            TargetGroupArn:
              Ref: EUMTargetGroup
        LoadBalancerArn: !Ref "LoadBalancer2"
        Port: 443
        Protocol: HTTPS
        Certificates: 
          - CertificateArn: arn:aws:acm:us-west-2:597823015631:certificate/9d6a1f3d-aa01-4d41-925e-440123441c3b
        SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
        
  EUSTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        Name: !Sub "${AWS::StackName}EUS-TG"
        Port: 9300
        Protocol: HTTP
        HealthCheckPort: "9300"
        TargetGroupAttributes:
          - Key: deregistration_delay.timeout_seconds
            Value: "20"
        VpcId: !ImportValue ais-provided-vpc-VPCID
        Tags:
          - Key: Project
            Value: !Sub "${AWS::StackName} Appd-EUSTG"
  EUSListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
          - Type: forward
            TargetGroupArn:
              Ref: EUSTargetGroup
        LoadBalancerArn: !Ref "LoadBalancer3"
        Port: 443
        Protocol: HTTPS
        Certificates: 
          - CertificateArn: arn:aws:acm:us-west-2:597823015631:certificate/9d6a1f3d-aa01-4d41-925e-440123441c3b
        SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
        
##Creating ASG 
  
  ConsoleAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: 
     - ConsoleEC2Template
     - ConsoleSecurityGroup
     - ConsoleInstanceProfile
     - AppdInstanceRole
    Properties:
      LaunchTemplate:
        LaunchTemplateName: !Sub "${AWS::StackName}-ConsoleEC2Template"
        Version: !GetAtt ConsoleEC2Template.LatestVersionNumber
      # LaunchConfigurationName:
      #   Ref: ConsoleLaunchConfiguration
      MaxSize: 1
      MinSize: 1
      DesiredCapacity: 1
      VPCZoneIdentifier:
        - "{{resolve:ssm:/GNCS/0/Vpcs/0/denali-provided-private-subnet/0/Id:1}}"

  ConsoleEC2Template:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName:  !Sub "${AWS::StackName}-ConsoleEC2Template"
      LaunchTemplateData:
        IamInstanceProfile:
          Name: !Ref ConsoleInstanceProfile
        ImageId:
          Ref: ImageId
        InstanceType:
          Ref: ConsoleInstanceType
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeType: gp3
              VolumeSize: '100'
              DeleteOnTermination: 'true'
              Encrypted: 'true'
          - DeviceName: /dev/xvdb
            Ebs:
              VolumeType: gp3
              VolumeSize: '1000'
              DeleteOnTermination: 'false'
              Encrypted: 'true'
        SecurityGroupIds:
          - Fn::ImportValue: ais-shared-services-sg-SS-SG
          - Ref: ConsoleSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            ${CommonUserData}
            ${APPDFileSystem}
        MetadataOptions:
          HttpEndpoint: enabled
          HttpPutResponseHopLimit: 2
          HttpTokens: required
          InstanceMetadataTags: enabled
        TagSpecifications:
          - ResourceType: "instance"
            Tags:
              - Key: "Name"
                Value: !Sub "${AWS::StackName}-Console"
              - Key: "Cluster_Name"
                Value: !Sub "${AWS::StackName}-Prod-APPD"
              - Key: "Project"
                Value: !Sub "${AWS::StackName}-Appd"
              - Key: "Enviroment"
                Value: !Sub "${AWS::StackName}-Prod"
                
  ConsoleSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        Fn::Sub: "${AWS::StackName} SG"
      VpcId:
        Fn::ImportValue: ais-provided-vpc-VPCID
      SecurityGroupEgress:
        - Description: Allow all outbound traffic
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - Description: Allow all Inbound traffic
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0    
  
  ConsoleInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: AppdInstanceRole
  
  AppdInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/AISSystemLogsPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess   
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/ais-permissions-boundaries"
      Tags:
        - Key: ref_architecture_instance_id
          Value: !Ref "AWS::StackName"
          
  ControlAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: 
     - ControlEC2Template
     - ControlSecurityGroup
     - ControlInstanceProfile
     - AppdInstanceRole
    Properties:
      LaunchTemplate:
        LaunchTemplateName: !Sub "${AWS::StackName}-ControlEC2Template"
        Version: !GetAtt ControlEC2Template.LatestVersionNumber
      # LaunchConfigurationName:
      #   Ref: ControlLaunchConfiguration
      TargetGroupARNs:
       - !Ref ControlTargetGroup
      MaxSize: 1
      MinSize: 1
      DesiredCapacity: 1
      VPCZoneIdentifier:
        - "{{resolve:ssm:/GNCS/0/Vpcs/0/denali-provided-private-subnet/0/Id:1}}"

  ControlEC2Template:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName:  !Sub "${AWS::StackName}-ControlEC2Template"
      LaunchTemplateData:
        IamInstanceProfile:
          Name: !Ref ControlInstanceProfile
        ImageId:
          Ref: ImageId
        InstanceType:
          Ref: ControlInstanceType
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeType: gp3
              VolumeSize: '100'
              DeleteOnTermination: 'true'
              Encrypted: 'true'
          - DeviceName: /dev/xvdb
            Ebs:
              VolumeType: gp3
              VolumeSize: '10000'
              DeleteOnTermination: 'false'
              Encrypted: 'true' 
        SecurityGroupIds:
          - Fn::ImportValue: ais-shared-services-sg-SS-SG
          - Ref: ControlSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            ${CommonUserData}
            ${APPDFileSystem}
        MetadataOptions:
          HttpEndpoint: enabled
          HttpPutResponseHopLimit: 2
          HttpTokens: required
          InstanceMetadataTags: enabled
        TagSpecifications:
          - ResourceType: "instance"
            Tags:
              - Key: "Name"
                Value: !Sub "${AWS::StackName}-Control"
              - Key: "Cluster_Name"
                Value: !Sub "${AWS::StackName}-Prod-APPD"
              - Key: "Project"
                Value: !Sub "${AWS::StackName}-Appd"
              - Key: "Enviroment"
                Value: !Sub "${AWS::StackName}-Prod"
 
  ControlSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        Fn::Sub: "${AWS::StackName} SG"
      VpcId:
        Fn::ImportValue: ais-provided-vpc-VPCID
      SecurityGroupEgress:
        - Description: Allow all outbound traffic
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - Description: Allow all Inbound traffic
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0      
  
  ControlInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: AppdInstanceRole
  
  EUMAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: 
     - EUMEC2Template
     - EUMSecurityGroup
     - EUMInstanceProfile
     - AppdInstanceRole
    Properties:
      LaunchTemplate:
        LaunchTemplateName: !Sub "${AWS::StackName}-EUMEC2Template"
        Version: !GetAtt EUMEC2Template.LatestVersionNumber
      # LaunchConfigurationName:
      #   Ref: EUMLaunchConfiguration
      TargetGroupARNs:
       - !Ref EUMTargetGroup
      MaxSize: 1
      MinSize: 1
      DesiredCapacity: 1
      VPCZoneIdentifier:
        - "{{resolve:ssm:/GNCS/0/Vpcs/0/denali-provided-private-subnet/0/Id:1}}"

  EUMEC2Template:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName:  !Sub "${AWS::StackName}-EUMEC2Template"
      LaunchTemplateData:
        IamInstanceProfile:
          Name: !Ref EUMInstanceProfile
        ImageId:
          Ref: ImageId
        InstanceType:
          Ref: EUMInstanceType
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeType: gp3
              VolumeSize: '100'
              DeleteOnTermination: 'true'
              Encrypted: 'true'
          - DeviceName: /dev/xvdb
            Ebs:
              VolumeType: gp3
              VolumeSize: '1500'
              DeleteOnTermination: 'false'
              Encrypted: 'true'   
        SecurityGroupIds:
          - Fn::ImportValue: ais-shared-services-sg-SS-SG
          - Ref: EUMSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            ${CommonUserData}
            ${APPDFileSystem}
        MetadataOptions:
          HttpEndpoint: enabled
          HttpPutResponseHopLimit: 2
          HttpTokens: required
          InstanceMetadataTags: enabled
        TagSpecifications:
          - ResourceType: "instance"
            Tags:
              - Key: "Name"
                Value: !Sub "${AWS::StackName}-EUM"
              - Key: "Cluster_Name"
                Value: !Sub "${AWS::StackName}-Prod-APPD"
              - Key: "Project"
                Value: !Sub "${AWS::StackName}-Appd"
              - Key: "Enviroment"
                Value: !Sub "${AWS::StackName}-Prod"
 
  EUMSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        Fn::Sub: "${AWS::StackName} SG"
      VpcId:
        Fn::ImportValue: ais-provided-vpc-VPCID
      SecurityGroupEgress:
        - Description: Allow all outbound traffic
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0 
      SecurityGroupIngress:
        - Description: Allow all Inbound traffic
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0    
  
  EUMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: AppdInstanceRole
        
  EUSAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: 
     - EUSEC2Template
     - EUSSecurityGroup
     - EUSInstanceProfile
     - AppdInstanceRole
    Properties:
      LaunchTemplate:
        LaunchTemplateName: !Sub "${AWS::StackName}-EUSEC2Template"
        Version: !GetAtt EUSEC2Template.LatestVersionNumber
      # LaunchConfigurationName:
      #   Ref: EUSLaunchConfiguration
      TargetGroupARNs:
       - !Ref EUSTargetGroup
      MaxSize: 5
      MinSize: 5
      DesiredCapacity: 5
      VPCZoneIdentifier:
        - "{{resolve:ssm:/GNCS/0/Vpcs/0/denali-provided-private-subnet/0/Id:1}}"

  EUSEC2Template:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName:  !Sub "${AWS::StackName}-EUSEC2Template"
      LaunchTemplateData:
        IamInstanceProfile:
          Name: !Ref EUSInstanceProfile
        ImageId:
          Ref: ImageId
        InstanceType:
          Ref: EUSInstanceType
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeType: gp3
              VolumeSize: '100'
              DeleteOnTermination: 'true'
              Encrypted: 'true'
          - DeviceName: /dev/xvdb
            Ebs:
              VolumeType: gp3
              VolumeSize: '10000'
              DeleteOnTermination: 'false'
              Encrypted: 'true'     
        SecurityGroupIds:
          - Fn::ImportValue: ais-shared-services-sg-SS-SG
          - Ref: EUSSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            ${CommonUserData}
            ${APPDFileSystem}
        MetadataOptions:
          HttpEndpoint: enabled
          HttpPutResponseHopLimit: 2
          HttpTokens: required
          InstanceMetadataTags: enabled
        TagSpecifications:
          - ResourceType: "instance"
            Tags:
              - Key: "Name"
                Value: !Sub "${AWS::StackName}-EUS"
              - Key: "Cluster_Name"
                Value: !Sub "${AWS::StackName}-Prod-APPD"
              - Key: "Project"
                Value: !Sub "${AWS::StackName}-Appd"
              - Key: "Enviroment"
                Value: !Sub "${AWS::StackName}-Prod"
 
  EUSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        Fn::Sub: "${AWS::StackName} SG"
      VpcId:
        Fn::ImportValue: ais-provided-vpc-VPCID
      SecurityGroupEgress:
        - Description: Allow all outbound traffic
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - Description: Allow all Inbound traffic
          IpProtocol: "-1"
          CidrIp: 0.0.0.0/0     
  
  EUSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: AppdInstanceRole

Outputs:
  ConsoleInstanceID:
    Description: The ConsoleAZ Instance ID
    Value: !Ref ConsoleAsg
  ControlTargetGroupArn:
    Description: ARN of the target group for Control nodes
    Value: !Ref ControlTargetGroup
  ControlInstanceID:
    Description: The Control Instance ID
    Value: !Ref ControlAsg
  EUSTargetGroupArn:
    Description: ARN of the target group for EUS nodes
    Value: !Ref EUSTargetGroup
