elasticsearch soft nproc 64000
elasticsearch hard nproc 64000
elasticsearch soft nofile 1048576
elasticsearch hard nofile 1048576
elasticsearch soft memlock unlimited
elasticsearch hard memlock unlimited
