identities:
  - ref: platform
    type: platform
    domain: aws
    name_autodetect: true
    identity_attestor: awsiid
  - ref: host
    type: host
    domain: aws
    name_autodetect: true
    identity_attestor: '$platform'
